SOURCES = Main.cpp Game.cpp PokeList.cpp ListNode.cpp BattleGround.cpp \
	Bulbasaur.cpp Charmander.cpp Pichu.cpp Squirtel.cpp Geodude.cpp \
	Blastoise.cpp Charizard.cpp Charmeleon.cpp FightingMethod.cpp Golem.cpp \
	Graveler.cpp Ivysaur.cpp Pikachu.cpp Player.cpp Pokemon.cpp Poliwag.cpp \
	Poliwhirl.cpp Poliwrath.cpp Raichu.cpp Venusaur.cpp Wartortle.cpp


all: pokemon

pokemon: 
	g++ -g -Wall -o pokemon $(SOURCES)



clean:
	rm -rf *.o pokemon
